### ISSUE TITLE
插件加载时出错

### ISSUE THREAD

**Issue by ab-Royo** [bot-ssttkkl/nonebot-plugin-error-alert#2]
```python
08-11 17:28:08 [INFO] nonebot | Current Env: prod
08-11 17:28:09 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
08-11 17:28:12 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
...
08-11 17:28:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_saa"
...
08-11 17:28:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
08-11 17:28:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_datastore"
08-11 17:28:27 [ERROR] nonebot | Failed to import "nonebot_plugin_error_alert"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot_plugin_error_alert\__init__.py", line 12, in <module>
    from . import matcher
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot_plugin_error_alert\matcher.py", line 12, in <module>
    from .subscribe import subscribe, unsubscribe, get_subscribe, SubscribeType
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot_plugin_error_alert\subscribe.py", line 20, in <module>
    mutex = Lock()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\locks.py", line 81, in __init__
    self._loop = events.get_event_loop()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```

**Comment by ssttkkl** [comment]
Python版本是多少？
________________________________
From: Roy ab ***@***.***>
Sent: Friday, August 11, 2023 5:32:23 PM
To: bot-ssttkkl/nonebot-plugin-error-alert ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bot-ssttkkl/nonebot-plugin-error-alert] 插件加载时出错 (Issue #2)


08-11 17:28:08 [INFO] nonebot | Current Env: prod
08-11 17:28:09 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
08-11 17:28:12 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
...
08-11 17:28:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_saa"
...
08-11 17:28:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
08-11 17:28:27 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_datastore"
08-11 17:28:27 [ERROR] nonebot | Failed to import "nonebot_plugin_error_alert"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot_plugin_error_alert\__init__.py", line 12, in <module>
    from . import matcher
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot_plugin_error_alert\matcher.py", line 12, in <module>
    from .subscribe import subscribe, unsubscribe, get_subscribe, SubscribeType
  File "C:\Users\Administrator\Desktop\QBot\main06\.venv\lib\site-packages\nonebot_plugin_error_alert\subscribe.py", line 20, in <module>
    mutex = Lock()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\locks.py", line 81, in __init__
    self._loop = events.get_event_loop()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

―

**Comment by ab-Royo** [comment]
Python 3.9.12
nonebot2-2.0.1
nonebot_plugin_apscheduler-0.3.0
nonebot_plugin_send_anything_anywhere-0.2.7
nonebot_plugin_datastore-1.1.0

**Comment by ab-Royo** [comment]
太奇怪了什么都没有动，今天重启机器人之后bug消失了？？？
抱歉打扰大佬了
